### ISSUE TITLE
Typos

### ISSUE THREAD

**Issue by qpwedev** [ton-blockchain/docs#23]
_Now_:
contract optionally generates **ougoing** messages
_Should be_:
contract optionally generates **outgoing** messages

_Now_:
There is a special mechanism of routing which move messages from **ougoing** queues
_Should be_:
There is a special mechanism of routing which move messages from **outgoing** queues

_Src_: https://ton.org/docs/#/overviews/TON_blockchain_overview

--------------------------------------------------------------------------------------------------------------

_Now_:
info (header of some sort, which describe source, destination and **othe** metadata)
_Should be_:
info (header of some sort, which describe source, destination and **other** metadata)

_Scr_: https://ton.org/docs/#/smart-contracts/messages

**Comment by alxjnk** [comment]
Now:
in TON for that pupose a special chain MasterChain
Should be:
in TON for that purpose a special chain MasterChain

Now:
thus any observer unambigously determine state of all multichain system at some masterchain block.
Should be:
thus any observer unambiguously determine state of all multichain system at some masterchain block.

Src: https://ton.org/docs/#/overviews/TON_blockchain_overview

Now:
After both separators, a undercore symbol _ may present, which means that tag is empty.
Should be:
After both separators, an underscore symbol _ may present, which means that tag is empty.

Src: https://ton.org/docs/#/overviews/TL-B

**Comment by nichitagutu** [comment]
_Now:_
Analogously, if some shards became too uno**c**upied they can be merged into one bigger shard.
_Should be:_
Analogously, if some shards became too uno**cc**upied they can be merged into one bigger shard.

_Now:_
Note that since ShardChain consis**t** of
_Should be:_
Note that since ShardChain consist**s** of

_Now:_
That way if we have 1 ShardChain which describ**e** events
_Should be:_
That way if we have 1 ShardChain which describe**s** events

_Now:_
we just divide (or split) that chain **to** two smaller ShardChains
_Should be:_
we just divide (or split) that chain **in** two smaller ShardChains

_Src:_ https://github.com/ton-blockchain/docs/blob/master/docs/overviews/TON_blockchain_overview.md#shards

_Now:_
For instance type Bool may ha**s** two constructors
_Should be:_
For instance type Bool may ha**ve** two constructors

_Src:_ https://github.com/ton-blockchain/docs/blob/master/docs/overviews/TL-B.md#scheme
